spring:
  jpa:
    hibernate:
      ddl-auto: update # create-drop, update
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/fmrte
    username: fmrte
    password: 'qorm12#$'
    
fmrte:
  apiKey : AIzaSyC1uJeDASliiuTZBOd_jz1Q5wSMjf9Edmg
  baseUrl : https://www.googleapis.com/youtube/v3/
  
---
spring:
   profiles: production
   datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fmrte
    username: fmrte
    password: 'qorm12#$'
    tomcat:
     test-while-idle: true
     validation-query: SELECT 1
     initial-size: 10
     max-active: 20
     min-idle: 10
     max-idle: 10
     max-wait: 3000
     connection-properties: autoReconnect=true;useUnicode=true;characterEncoding=utf-8
logging:
  config: classpath:logback-production.xml